name: geog0133_env

dependencies:
    - jupyterlab
    - notebook
    - nbconvert
    - ipykernel
    - ipywidgets
    - ipyleaflet
    - widgetsnbextension
    - matplotlib
    - pandas
    - jupyter_contrib_nbextensions
    - widgetsnbextension
    - signaturesimulator