name: geog0133_env

dependencies:
    - python2.7
    - jupyterlab
    - notebook
    - nbconvert
    - ipykernel
    - ipywidgets
    - ipyleaflet
    - widgetsnbextension
    - matplotlib
    - pandas
    - jupyter_contrib_nbextensions
    - widgetsnbextension
    - matplotlib>=1.4.3,<3
    - C
    - C++