name: geog0133_env

dependencies:
    - python>=2.7,<3
    - jupyterlab
    - notebook
    - nbconvert
    - ipykernel
    - ipywidgets
    - ipyleaflet
    - widgetsnbextension
    - pandas
    - jupyter_contrib_nbextensions
    - widgetsnbextension
    - libc
    - matplotlib>=1.4.3,<3