#!/bin/bash

# pip install git+https://github.com/jgomezdans/GomezEngine.git
#sudo apt-get install libgfortran3
#sudo apt-get install lib32gfortran3 libx32gfortran3
curl https://sh.rustup.rs -sSf | sh -s -- -y
echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> ~/.bashrc
pip install signaturesimulator
jupyter contrib nbextension install --user
jupyter nbextension enable --py widgetsnbextension
jupyter nbextension enable python-markdown/main

# Install a JupyterLab extension for demonstration purposes
jupyter labextension install @jupyterlab/geojson-extension
jupyter labextension install @jupyter-widgets/jupyterlab-manager

jupyter trust *.ipynb